# Generated by Django 3.2.4 on 2021-06-24 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_keeper', '0002_auto_20210624_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.RemoveField(
            model_name='round',
            name='points',
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='players',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='game_keeper.player'),
            preserve_default=False,
        ),
    ]
