# Generated by Django 3.2.4 on 2021-06-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_keeper', '0003_auto_20210624_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='players',
            new_name='player',
        ),
    ]
