# Generated by Django 3.2.4 on 2021-06-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keeper', '0004_rename_players_round_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rounds',
        ),
        migrations.AddField(
            model_name='game',
            name='rounds',
            field=models.ManyToManyField(to='game_keeper.Round'),
        ),
    ]
