# Generated by Django 3.2.4 on 2021-06-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keeper', '0005_auto_20210624_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='player',
        ),
        migrations.AddField(
            model_name='round',
            name='players',
            field=models.ManyToManyField(to='game_keeper.Player'),
        ),
    ]
