# Generated by Django 3.2.4 on 2021-06-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_keeper', '0006_auto_20210624_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
